--- 
# Input Output Info
files:
  - object_name: manga-8144-3702-LINCUBE #name of the specfile
    object_type: IFS #type of the specfile: IFS for datacube or OneD for single spectra
    test: True #flag to run the full analysis
    it: 0 #i index for test, default nx/2
    jt: 0 #j index for test, default ny/2
    name_out: None #name of the output files
    mask: None #name of the mask map
    path: ../example_data/ #path to the data cubes
    path_out: outputs/ #path of the output files
    ncpus: 10 #number of CPUs'
    sprogressd: False #fdeactivate the progress bar
    
    # Wavelenght Range
    wave_ini: 6475.0 #initial wave vale, it overrides wave_range if not None
    wave_fin: 6660.0 #final wave vale, it overrides wave_range if not None
    wave_range: HaNII #name of the spectral range, options are Hbeta, Halpha and None

    # Model Components
    kskew: False #flag to run skew line profile mode
    lorentz: False #activate the lorenztiant broad profile
    outflow: False #flag to run outflow line profile mode
    error: False #flag to run autocalculate the error vector  
    line_config: line_prop.yml #configuration file of the emision lines
    line_config_path: '' #path to the configuration file of the emision lines

    # Object Info
    zt: 0.09785 #redshift of the object
    fluxf: 1.0 #flux scale factor  
    bcont: False #flag to run deactivate autosubstract continum
...
