--- 
# Input Output Info
files:
  - object_name: spec-5715-56657-0166 #name of the specfile
    object_type: OneD #type of the specfile: IFS for datacube or OneD for single spectra
    name_out: None #name of the output files
    path: ../example_data/ #path to the data files
    path_out: outputs/ #path of the output files
    ncpus: 10 #number of CPUs'
    input_format: SDSS #format of the input file, options are TableFits, IrafFits, CSV, ASCII
    
    # Wavelenght Range
    #wave_ini: 4700.0 #initial wave vale, it overrides wave_range if not None
    #wave_fin: 5050.0 #final wave vale, it overrides wave_range if not None
    #wave_range: HbOIII #name of the spectral range, options are Hbeta, Halpha and None
    wave_ini: 6475.0
    wave_fin: 6650.0
    wave_range: HaNIII 

    # Model Components
    kskew: False #flag to run skew line profile mode
    lorentz: False #activate the lorenztiant broad profile
    outflow: False #flag to run outflow line profile mode
    error: False #flag to run autocalculate the error vector
    line_config: line_prop_Ha.yml #configuration file of the emision lines
    line_config_path: '' #path to the configuration file of the emision lines
    #rvel: 500.0 #narrow velocity shift range

    # Object Info
    zt: 0.0255 #redshift of the object
    fluxf: 1.0 #flux scale factor  
    bcont: False #flag to run deactivate autosubstract continum
...
